Example 2
DiabloZ/Android pull request #2
Opened 2020-09-08 15:14 UTC by DiabloZ

Сереж, глянь пожалуйста

2020-09-08 20:27 UTC, industradamus requested changes

2020-09-08 20:27 UTC, s-buvaka commented on Example_Android_Academy/app/Example_2/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Вот от этого лучше избавиться. Прям удали зависимость и посмотри что сломается и замени на более новое. Если сам не поймешь, что менять то напиши мне, вместе разберемся
`implementation 'androidx.legacy:legacy-support-v4:1.0.0'`

2020-09-08 20:27 UTC, s-buvaka commented on Example_Android_Academy/app/Example_2/build.gradle
> +    testImplementation 'junit:junit:4.12'
Вообще а build.gradle удаляй все, что не используется. Ты пока тесты не пишешь - удали. В целом для тебя сейчас пох, но если будешь писать тестовое куда-то (на работу или на курсы какие-то) на это часто обращают внимание. 

Второй момент: разделяй зависимости и подписывай для лучшего чтения. Когда у тебя тут будет 10ок другой зависимостей потом найти что0то будет трудно. Тут должен быть порядок. 

Вот небольшой пример зависимостей:

```
//Retrofit
    def retrofit2_version = '2.9.0'
    def okhttp3_version = '4.8.1'
    implementation "com.squareup.retrofit2:retrofit:$retrofit2_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit2_version"
    implementation "com.squareup.okhttp3:logging-interceptor:$okhttp3_version"
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.8.1'
    testImplementation "com.squareup.okhttp3:mockwebserver:$okhttp3_version"

    //RX Java
    implementation group: 'io.reactivex.rxjava2', name: 'rxandroid', version: '2.1.1'
    implementation group: 'io.reactivex.rxjava2', name: 'rxjava', version: '2.2.19'
    implementation("io.reactivex.rxjava2:rxkotlin:2.4.0")

    //Glide
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    implementation 'jp.wasabeef:glide-transformations:4.1.0'
```

Каждая отдельная зависимость отделена пробелом и комментом.

2020-09-08 20:27 UTC, s-buvaka commented on Example_Android_Academy/app/Example_2/src/androidTest/java/com/example/example_2/ExampleInstrumentedTest.java
> +package com.example.example_2;
Удали весь файл. Но это опять же замечание на будущее. На это так же обращают внимание. Нет тестов - значит файл не нужен

2020-09-08 20:27 UTC, s-buvaka commented on Example_Android_Academy/app/Example_2/src/main/AndroidManifest.xml
> +        <activity android:name=".classes.MainActivity" android:windowSoftInputMode="adjustPan">
Разделяй пробельчиками каждый новый блок (активити, сервисы и др. )

2020-09-08 20:27 UTC, s-buvaka commented on Example_Android_Academy/app/Example_2/src/main/java/com/example/example_2/constants/Constants.java
> +    public static final String SUBJECT = "me?";
Не стоит создавать классы которые хранят в себе гору всяких констант. Если эта константа юзается только в 1 месте, то там ее и создавай приватную. Если она юзается только в одной папке то создай где-то в этой папке. Короч область видимости должна быть минимально необходимая.

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/java/com/example/example_2/fragments/ContentFragment.java
> +    protected EditText fieldMessage;
Зачем тебе `protected`? Ты будешь наследоваться от этого фрагмента? Соменваюсь, а если да то трижды подумай. Наследование - ЗЛО=) (но иногда оно очень нужно и полезно). `private` ставь

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/java/com/example/example_2/fragments/ContentFragment.java
> +    protected Context context;
Убей это поле. Внутри фрагмента контекст всегда можно получить 
```
requireContext()
requireActivity()
```

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/java/com/example/example_2/fragments/ContentFragment.java
> +    protected Button sendMessageBtn;
Кстати, небольшой лайфхак который могут оценить на собесе (но который с приходом котлина будет не нужен, да и в целом не особо часто полезен):
Если у тебя есть кнопка с которой ты кроме назначение clickListener ничего не делаешь, то объявляй ее как View. Так ты потом сможешь без проблем заменить ее на любую другую View. 

У View так же можно назначить clickListener, но это базовый класс над всеми View, а если тебе не нужны детали реализации то лучше использовать более обощенные типы.

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/java/com/example/example_2/fragments/ContentFragment.java
> +            case R.id.telegramBtn:
Для таких штук лучше не опираться на id. Уж лучше создать enum  
```
enum  Message {
    TELEGRAM,
    WHATS_APP
}
```

id это штука ненадежная. А еще лучше не создавать enum, а просто вот этот кусок кода `Uri.parse(Constants.URI_whatsapp)` отдельно выполнять в самом листенере и просто передавать в методе где готовая ссылка будет отправляться в интент

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/java/com/example/example_2/fragments/ContentFragment.java
> +    private void sendMailFromIntent() {
```
private void sendMailFromIntent() {
        Intent intent = new Intent(Intent.ACTION_SEND);
        intent.setType("*/*")
                .putExtra(Intent.EXTRA_EMAIL, Constants.EMAIL)
                .putExtra(Intent.EXTRA_SUBJECT, Constants.SUBJECT)
                .putExtra(Intent.EXTRA_STREAM, Constants.ATTACHMENT)
                .putExtra(Intent.EXTRA_TEXT, fieldMessage.getText().toString());
        
        if (intent.resolveActivity(context.getPackageManager()) != null) startActivity(intent);
    }
```

Вот так чуточку аккуратнее. Методы Intent реализуют паттерн Builder. Т.е. они возвращают ссылку на самого себя и ты можешь вот такие цепочки строить. 

Принципиально разницы 0, но так более аккуратно и читабельно

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/res/layout-land/activity_main.xml
> +        android:background="#050505"
Вот цвета лучше выносить в ресурсы. Обычно в приложении их достаточно ограниченный набор и их нужно переиспользовать. Они обычно если меняются то все вместе

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/res/layout-land/activity_main.xml
> +        app:layout_constraintBottom_toBottomOf="parent"
Зачем тут констрейнты если у тебя LinearLayout?=) Следи за этим

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/res/layout-land/activity_main.xml
> +            app:layout_constraintBottom_toBottomOf="parent"
Аналогично, констрейнты выпили

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/res/layout-land/activity_main.xml
> +            app:layout_constraintBottom_toBottomOf="parent"
И дальше по коду пройдись проверь

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/res/layout-land/activity_main.xml
> +        <ScrollView
По-моему в ScrollView должен быть LinearLayout вложен. А иначе он тут по идее не даст ничего. (но это не точно, проверь)

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/res/layout/fragment_content.xml
> +            android:layout_marginStart="25dp"
По рекомендациям Google все отступы должны быть кратны 2, а лучше 4. Это связано с тем, что при масштабировании на разных экранах эти цифры могут меняться (почитай про то что такое dp и как потом это все в пиксели переводится если не знаешь). Например 25* 1.5 получится 37.5 и потеряется 1 пиксель.

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/main/res/values-ru/strings.xml
> +    <string name="app_name">Example_2</string>
В ресурах разные экраны или какие-то блоки Ui (тут зависит от построения твоего приложения и т.д) лучше разделять пробелами и оставлять комменты

```
<-- MainActivity -->
 <string name="fullName">Сухов Виталий</string>
 <string name="android_student_department">Студенческий департамент</string>

<--SecondActivity-->
 <string name="fullName">Сухов Виталий</string>
 <string name="android_student_department">Студенческий департамент</string>
```
Примерно по такому принципу. Представь сколько тут всего в реальном приложении...

2020-09-08 20:27 UTC, industradamus commented on Example_Android_Academy/app/Example_2/src/test/java/com/example/example_2/ExampleUnitTest.java
> +
Выпили если тут твоих тестов нет

2020-09-10 09:01 UTC, DiabloZ commented on Example_Android_Academy/app/Example_2/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Удалил, ничего не поломалось.

2020-09-10 09:44 UTC, DiabloZ commented on Example_Android_Academy/app/Example_2/build.gradle
> +    testImplementation 'junit:junit:4.12'
Удалил ненужны зависимости, описал имеющиеся.

2020-09-10 09:45 UTC, DiabloZ commented on Example_Android_Academy/app/Example_2/src/androidTest/java/com/example/example_2/ExampleInstrumentedTest.java
> +package com.example.example_2;
удалил.

2020-09-10 09:46 UTC, DiabloZ commented on Example_Android_Academy/app/Example_2/src/main/AndroidManifest.xml
> +        <activity android:name=".classes.MainActivity" android:windowSoftInputMode="adjustPan">
Разделил.

2020-09-10 09:56 UTC, DiabloZ commented on Example_Android_Academy/app/Example_2/src/main/java/com/example/example_2/constants/Constants.java
> +    public static final String SUBJECT = "me?";
Удалил класс констант, закинул всю информацию в фрагмент, поменял пути к переменным, проверил работоспособность.

2020-09-10 09:58 UTC, DiabloZ commented on Example_Android_Academy/app/Example_2/src/main/java/com/example/example_2/fragments/ContentFragment.java
> +    protected EditText fieldMessage;
Затупил увидев, что окружение подчёркивало в привате их будто они не используются. Сейчас проверил, действительно работает. В будущем не допущу(постараюсь) этой ошибки.

2020-09-10 13:27 UTC, merged